project:
  type: website
  resources: 
    - workshops
    - teaching
    #- papers
  render:
    - "*qmd"
    - "*ipynb"
    - "!papers/*/*qmd"
    - "!teaching/courses/2022_lin517/src"
    - "!**/*_files/"

filters:
    - codeblocklabel
    
website:
  google-analytics: 
    tracking-id: "G-C00S3NPL7B"
    anonymize-ip: true
  cookie-consent: true
  title: "Josef Fruehwald"
  favicon: assets/logo.svg
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: research/index.qmd
        text: Research
      - href: software/index.qmd
        text: Software
      - href: teaching/index.qmd
        text: Teaching
      - href: teaching/courses/2017_lsa/index.qmd
        text: "LSA 2017 Course"
    right:
      - href: https://jofrhwld.github.io/blog/
        text: Blog
        icon: newspaper
      - href: https://bsky.app/profile/jofrhwld.bsky.social
        icon: clouds
        text: bsky
      - href: https://github.com/JoFrhwld
        icon: github
  sidebar:
    - title: "Home"
    - title: "Research"
      contents: 
        - research/index.qmd
    - title: "LSA 2017 Course"
      contents: 
        - teaching/courses/2017_lsa/index.qmd
        - auto: teaching/courses/2017_lsa/lectures/
    
format:
  html:
    theme:
      light:
        - flatly
        - styles/light.scss
        - styles/styles.scss
      dark:
        - darkly
        - styles/dark.scss
        - styles/styles.scss
    toc: true
    

editor: visual

