project:
  type: website
  render:
    - index.qmd

website:
  title: "Josef Fruehwald"
  favicon: fav/favicon-32x32.png
  navbar:
    left:
      - href: index.qmd
        text: Home

format:
  html:
    theme: darkly
    css: styles.css
    toc: true

editor: visual

