project:
  type: website
  resources: 
    - workshops
    - teaching
    - papers
  render:
    - "*.qmd"
    - "!papers/*/*qmd"
    - "!teaching/courses/2022_lin517/src"
    - "!*/skeleton"
website:
  title: "Josef Fruehwald"
  favicon: fav/favicon-32x32.png
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: research/index.qmd
        text: Research
      - href: teaching/index.qmd
        text: Teaching
format:
  html:
    theme:
      light: flatly
      dark: darkly
    css: styles.css
    toc: true

editor: visual

