project:
  type: website
  resources: 
    - workshops
    - teaching
    - data
    #- papers
  render:
    - "*qmd"
    - "*ipynb"
    - "!papers/*/*qmd"
    - "!teaching/courses/2022_lin517/src"
    - "!**/*_files/"

filters:
    - codeblocklabel
    
execute:
  freeze: auto  # re-render only when source changes    
    
website:
  google-analytics: 
    tracking-id: "G-C00S3NPL7B"
    anonymize-ip: true
  cookie-consent: true
  title: "Josef Fruehwald"
  favicon: assets/logo.svg
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: research/index.qmd
        text: Research
      - href: software/index.qmd
        text: Software
      - href: teaching/index.qmd
        text: Teaching
      - href: teaching/courses/2017_lsa/index.qmd
        text: "LSA 2017 Course"
    right:
      - href: https://jofrhwld.github.io/blog/
        text: Blog
        icon: newspaper
      - href: https://bsky.app/profile/jofrhwld.bsky.social
        icon: clouds
        text: bsky
      - href: https://github.com/JoFrhwld
        icon: github
  sidebar:
    - title: "Home"
    - title: "Research"
      contents: 
        - research/index.qmd
        - make_qmd.ipynb
        - section: "By Year"
          contents:
            - section: "2020s"
              contents: 
                - text: "2023"
                  href: "research/#2023"            
                - text: "2022"
                  href: "research/#2022"  
                - text: "2021"
                  href: "research/#2021"          
                - text: "2020"
                  href: "research/#2020"
            - section: "2010s"
              contents:
                - text: "2019"
                  href: "research/#2019"
                - text: "2018"
                  href: "research/#2018"
                - text: "2017"
                  href: "research/#2017"
                - text: "2016"
                  href: "research/#2016"
                - text: "2015"
                  href: "research/#2015"              
                - text: "2014"
                  href: "research/#2014"
                - text: "2013"
                  href: "research/#2013"
                - text: "2012"
                  href: "research/#2012"              
                - text: "2011"
                  href: "research/#2011"
            - section: "2000s"
              contents:
                - text: "2008"
                  href: "research/#2008"              
                - text: "2007"
                  href: "research/#2007"              
    - title: "LSA 2017 Course"
      contents: 
        - teaching/courses/2017_lsa/index.qmd
        - auto: teaching/courses/2017_lsa/lectures/
    
format:
  html:
    theme:
      light:
        - flatly
        - styles/light.scss
        - styles/styles.scss
      dark:
        - darkly
        - styles/dark.scss
        - styles/styles.scss
    toc: true
    smooth-scroll: true
    
editor: visual

