project:
  type: website
  render:
    - index.qmd
    - research/*

website:
  title: "Josef Fruehwald"
  favicon: fav/favicon-32x32.png
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: research/index.qmd
        text: research
format:
  html:
    theme: darkly
    css: styles.css
    toc: true

editor: visual

