name: Build Site
on:
  push:
    branches: ["master"]
  workflow_dispatch: 

jobs:
  build-docs:
     runs-on: ubuntu-latest
     steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 2
      - uses: actions/setup-python@v2
        with:
          python-version: "3.11"
      - uses: r-lib/actions/setup-r@v2
      - name: Install dependencies
        run: |
          python -m pip install -r requirements.txt
      - uses: r-lib/actions/setup-renv@v2
      - name: Install Reticulate
        run: Rscript -e 'renv::install("reticulate")'
      - name: Set up quarto
        uses: quarto-dev/quarto-actions/setup@v2
      - name: Build Research pages
        run: |
          python make_research_qmd.py --zotero_key  ${{ secrets.ZOTERO_KEY }}
      - name: Commit if diff
        run: |
          if git diff --exit-code; then
            echo "No Changes"
          else:
            git config user.name 'bot'
            git config user.email '...'
            git add research/papers/*
            git commit -m "gh workflow build [skip actions]" --no-verify
            git push
          fi
      - name: Render and publish to gh pages
        uses: quarto-dev/quarto-actions/publish@v2
        with:
          target: gh-pages